-- local blink_cmp = require("blink.cmp")
--
-- blink_cmp.setup({
--   -- Presets for accept key: 'default' (C-y), 'super-tab' (Tab), 'enter', 'none'
--   -- Common mappings: C-space open menu/docs, C-n/p navigate, C-e hide, C-k toggle sig help
--   keymap = { preset = "enter" },
--
--   appearance = {
--     -- 'mono' for Nerd Font Mono, aligns icons nicely; 'normal' for Nerd Font
--     nerd_font_variant = "mono",
--   },
--
--   completion = {
--     -- Docs popup shows only when triggered (not automatically)
--     documentation = { auto_show = true },
--   },
--
--   sources = {
--     -- Default providers, can be extended elsewhere without redefining
--     default = { "lsp", "path", "snippets", "buffer" },
--   },
--
--   fuzzy = {
--     -- Rust fuzzy matcher for better perf and typo tolerance
--     -- Fallback to Lua matcher with warning if Rust not available
--     implementation = "prefer_rust_with_warning",
--   },
-- })
