return {
  { "tpope/vim-sleuth",    lazy = false },
  { "tpope/vim-abolish",   event = "VeryLazy" },
  { "tpope/vim-fugitive",  event = "VeryLazy" },
  { "tpope/vim-surround",  event = "VeryLazy" },
  { "tpope/vim-repeat",    event = "VeryLazy" },
  { "tpope/vim-rsi",       event = "VeryLazy" },
  { "christoomey/vim-tmux-navigator", event = "VeryLazy" },
  { "romainl/vim-cool",    event = "VeryLazy" },
  { "godlygeek/tabular",   event = "VeryLazy" },
  { "vim-test/vim-test",   event = "VeryLazy" },
  { "nvim-lua/plenary.nvim", lazy = true },
  { "nvim-lua/popup.nvim",   lazy = true },
  { "ThePrimeagen/harpoon",  event = "VeryLazy", dependencies = { "nvim-lua/plenary.nvim" } },
  { "ruifm/gitlinker.nvim",  event = "VeryLazy", opts = true, dependencies = { "nvim-lua/plenary.nvim" } },
  { "numToStr/Comment.nvim", event = "VeryLazy", config = true },
  { "folke/noice.nvim",      lazy = true, opts = {}, dependencies = { "MunifTanjim/nui.nvim" } },
  { "stevearc/quicker.nvim", event = "FileType qf", opts = {}, config = function() require("quicker").setup() end },
}
