env:
  TERM: xterm-256color

key_bindings:
  - { key: A, mods: Alt, chars: "\ea" }
  - { key: B, mods: Alt, chars: "\eb" }
  - { key: C, mods: Alt, chars: "\ec" }
  - { key: D, mods: Alt, chars: "\ed" }
  - { key: E, mods: Alt, chars: "\ee" }
  - { key: F, mods: Alt, chars: "\ef" }
  - { key: G, mods: Alt, chars: "\eg" }
  - { key: H, mods: Alt, chars: "\eh" }
  - { key: I, mods: Alt, chars: "\ei" }
  - { key: J, mods: Alt, chars: "\ej" }
  - { key: K, mods: Alt, chars: "\ek" }
  - { key: L, mods: Alt, chars: "\el" }
  - { key: M, mods: Alt, chars: "\em" }
  - { key: N, mods: Alt, chars: "\en" }
  - { key: O, mods: Alt, chars: "\eo" }
  - { key: P, mods: Alt, chars: "\ep" }
  - { key: Q, mods: Alt, chars: "\eq" }
  - { key: R, mods: Alt, chars: "\er" }
  - { key: S, mods: Alt, chars: "\es" }
  - { key: T, mods: Alt, chars: "\et" }
  - { key: U, mods: Alt, chars: "\eu" }
  - { key: V, mods: Alt, chars: "\ev" }
  - { key: W, mods: Alt, chars: "\ew" }
  - { key: X, mods: Alt, chars: "\ex" }
  - { key: Y, mods: Alt, chars: "\ey" }
  - { key: Z, mods: Alt, chars: "\ez" }

window:
  decorations: Buttonless
  padding:
    x: 10
    y: 5

font:
  normal:
    family: "JetBrainsMono Nerd Font Mono"
    style: Regular

  bold:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold

  italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Italic

  # Point size of the font
  size: 15.0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

# Nightfox Alacritty Colors
# Style: carbonfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/carbonfox/nightfox_alacritty.yml
colors:
  # Default colors
  primary:
    background: '0x161616'
    foreground: '0xf2f4f8'
  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xee5396'
    green:   '0x25be6a'
    yellow:  '0x08bdba'
    blue:    '0x78a9ff'
    magenta: '0xbe95ff'
    cyan:    '0x33b1ff'
    white:   '0xdfdfe0'
  # Bright colors
  bright:
    black:   '0x484848'
    red:     '0xf16da6'
    green:   '0x46c880'
    yellow:  '0x2dc7c4'
    blue:    '0x8cb6ff'
    magenta: '0xc8a5ff'
    cyan:    '0x52bdff'
    white:   '0xe4e4e5'
  indexed_colors:
    - { index: 16, color: '0x3ddbd9' }
    - { index: 17, color: '0xff7eb6' }
