env:
  TERM: xterm-256color
  COLORTERM: truecolor

window:
  decorations: Buttonless
  padding:
    x: 10 
    y: 5

font:
  normal:
    family: "Hack Nerd Font Mono"
    style: Regular

  bold:
    family: "Hack Nerd Font Mono"
    style: Bold

  italic:
    family: "Hack Nerd Font Mono"
    style: Italic

  # Point size of the font
  size: 14.0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true