
import=[
# "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
"~/.config/alacritty/themes/themes/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations="Buttonless"

[window.padding]
x=5
y=10

[font]
size = 12

[font.normal]
family="JetBrainsMono Nerd Font Mono"
style="Regular"

[font.bold]
family="JetBrainsMono Nerd Font Mono"
style="Bold"

[font.italic]
family="JetBrainsMono Nerd Font Mono"
style="Italic"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
