
import=[
# "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
# "~/.config/alacritty/themes/themes/rose-pine.toml"
"~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations="Buttonless"
option_as_alt="Both"

[window.padding]
x=5
y=10

[font]
size = 15

[font.normal]
family="JetBrainsMono Nerd Font Mono"
style="Regular"

[font.bold]
style="Bold"

[font.italic]
style="Italic"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001Bf" },
  { key = "Left",  mods = "Alt", chars = "\u001Bb" },
]
