env:
  TERM: xterm-256color

key_bindings:
  - { key: A,         mods: Alt,       chars: "\x1ba"                       }
  - { key: B,         mods: Alt,       chars: "\x1bb"                       }
  - { key: C,         mods: Alt,       chars: "\x1bc"                       }
  - { key: D,         mods: Alt,       chars: "\x1bd"                       }
  - { key: E,         mods: Alt,       chars: "\x1be"                       }
  - { key: F,         mods: Alt,       chars: "\x1bf"                       }
  - { key: G,         mods: Alt,       chars: "\x1bg"                       }
  - { key: H,         mods: Alt,       chars: "\x1bh"                       }
  - { key: I,         mods: Alt,       chars: "\x1bi"                       }
  - { key: J,         mods: Alt,       chars: "\x1bj"                       }
  - { key: K,         mods: Alt,       chars: "\x1bk"                       }
  - { key: L,         mods: Alt,       chars: "\x1bl"                       }
  - { key: M,         mods: Alt,       chars: "\x1bm"                       }
  - { key: N,         mods: Alt,       chars: "\x1bn"                       }
  - { key: O,         mods: Alt,       chars: "\x1bo"                       }
  - { key: P,         mods: Alt,       chars: "\x1bp"                       }
  - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
  - { key: R,         mods: Alt,       chars: "\x1br"                       }
  - { key: S,         mods: Alt,       chars: "\x1bs"                       }
  - { key: T,         mods: Alt,       chars: "\x1bt"                       }
  - { key: U,         mods: Alt,       chars: "\x1bu"                       }
  - { key: V,         mods: Alt,       chars: "\x1bv"                       }
  - { key: W,         mods: Alt,       chars: "\x1bw"                       }
  - { key: X,         mods: Alt,       chars: "\x1bx"                       }
  - { key: Y,         mods: Alt,       chars: "\x1by"                       }
  - { key: Z,         mods: Alt,       chars: "\x1bz"                       }

window:
  decorations: Buttonless
  padding:
    x: 10
    y: 5

font:
  normal:
    family: "JetBrains Mono"
    style: Regular

  bold:
    family: "JetBrains Mono"
    style: Bold

  italic:
    family: "JetBrains Mono"
    style: Italic

  # Point size of the font
  size: 15.0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

# github Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x22272e'
    foreground: '0x768390'

  # Normal colors
  normal:
    black:   '0x545d68'
    red:     '0xf47067'
    green:   '0x57ab5a'
    yellow:  '0xc69026'
    blue:    '0x539bf5'
    magenta: '0xb083f0'
    cyan:    '0x39c5cf'
    white:   '0x909dab'

  # Bright colors
  bright:
    black:   '0x636e7b'
    red:     '0xff938a'
    green:   '0x6bc46d'
    yellow:  '0xdaaa3f'
    blue:    '0x6cb6ff'
    magenta: '0xdcbdfb'
    cyan:    '0x56d4dd'
    white:   '0xcdd9e5'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xff938a' }