
import=[
"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
# "~/.config/alacritty/themes/themes/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations="Buttonless"
padding.x=5
padding.y=10

[font]
size = 12
normal.family="JetBrainsMono Nerd Font Mono"
normal.style="Regular"
bold.family="JetBrainsMono Nerd Font Mono"
bold.style="Bold"
italic.family="JetBrainsMono Nerd Font Mono"
italic.style="Italic"

