env:
  TERM: xterm-256color

key_bindings:
  - { key: A, mods: Alt, chars: "\ea" }
  - { key: B, mods: Alt, chars: "\eb" }
  - { key: C, mods: Alt, chars: "\ec" }
  - { key: D, mods: Alt, chars: "\ed" }
  - { key: E, mods: Alt, chars: "\ee" }
  - { key: F, mods: Alt, chars: "\ef" }
  - { key: G, mods: Alt, chars: "\eg" }
  - { key: H, mods: Alt, chars: "\eh" }
  - { key: I, mods: Alt, chars: "\ei" }
  - { key: J, mods: Alt, chars: "\ej" }
  - { key: K, mods: Alt, chars: "\ek" }
  - { key: L, mods: Alt, chars: "\el" }
  - { key: M, mods: Alt, chars: "\em" }
  - { key: N, mods: Alt, chars: "\en" }
  - { key: O, mods: Alt, chars: "\eo" }
  - { key: P, mods: Alt, chars: "\ep" }
  - { key: Q, mods: Alt, chars: "\eq" }
  - { key: R, mods: Alt, chars: "\er" }
  - { key: S, mods: Alt, chars: "\es" }
  - { key: T, mods: Alt, chars: "\et" }
  - { key: U, mods: Alt, chars: "\eu" }
  - { key: V, mods: Alt, chars: "\ev" }
  - { key: W, mods: Alt, chars: "\ew" }
  - { key: X, mods: Alt, chars: "\ex" }
  - { key: Y, mods: Alt, chars: "\ey" }
  - { key: Z, mods: Alt, chars: "\ez" }

window:
  decorations: Buttonless
  padding:
    x: 10
    y: 5

font:
  normal:
    family: "JetBrainsMono Nerd Font Mono"
    style: Regular

  bold:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold

  italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Italic

  # Point size of the font
  size: 15.0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: "0x191724"
    foreground: "0xe0def4"
  cursor:
    text: "0xe0def4"
    cursor: "0x524f67"
  vi_mode_cursor:
    text: "0xe0def4"
    cursor: "0x524f67"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: "0xe0def4"
    background: "0x403d52"
  normal:
    black: "0x26233a"
    red: "0xeb6f92"
    green: "0x31748f"
    yellow: "0xf6c177"
    blue: "0x9ccfd8"
    magenta: "0xc4a7e7"
    cyan: "0xebbcba"
    white: "0xe0def4"
  bright:
    black: "0x6e6a86"
    red: "0xeb6f92"
    green: "0x31748f"
    yellow: "0xf6c177"
    blue: "0x9ccfd8"
    magenta: "0xc4a7e7"
    cyan: "0xebbcba"
    white: "0xe0def4"
  hints:
    start:
      foreground: "#908caa"
      background: "#1f1d2e"
    end:
      foreground: "#6e6a86"
      background: "#1f1d2e"
