env:
  TERM: xterm-256color

key_bindings:
  - { key: A,         mods: Alt,       chars: "\x1ba"                       }
  - { key: B,         mods: Alt,       chars: "\x1bb"                       }
  - { key: C,         mods: Alt,       chars: "\x1bc"                       }
  - { key: D,         mods: Alt,       chars: "\x1bd"                       }
  - { key: E,         mods: Alt,       chars: "\x1be"                       }
  - { key: F,         mods: Alt,       chars: "\x1bf"                       }
  - { key: G,         mods: Alt,       chars: "\x1bg"                       }
  - { key: H,         mods: Alt,       chars: "\x1bh"                       }
  - { key: I,         mods: Alt,       chars: "\x1bi"                       }
  - { key: J,         mods: Alt,       chars: "\x1bj"                       }
  - { key: K,         mods: Alt,       chars: "\x1bk"                       }
  - { key: L,         mods: Alt,       chars: "\x1bl"                       }
  - { key: M,         mods: Alt,       chars: "\x1bm"                       }
  - { key: N,         mods: Alt,       chars: "\x1bn"                       }
  - { key: O,         mods: Alt,       chars: "\x1bo"                       }
  - { key: P,         mods: Alt,       chars: "\x1bp"                       }
  - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
  - { key: R,         mods: Alt,       chars: "\x1br"                       }
  - { key: S,         mods: Alt,       chars: "\x1bs"                       }
  - { key: T,         mods: Alt,       chars: "\x1bt"                       }
  - { key: U,         mods: Alt,       chars: "\x1bu"                       }
  - { key: V,         mods: Alt,       chars: "\x1bv"                       }
  - { key: W,         mods: Alt,       chars: "\x1bw"                       }
  - { key: X,         mods: Alt,       chars: "\x1bx"                       }
  - { key: Y,         mods: Alt,       chars: "\x1by"                       }
  - { key: Z,         mods: Alt,       chars: "\x1bz"                       }

window:
  decorations: Buttonless
  padding:
    x: 10
    y: 5

font:
  normal:
    family: "JetBrainsMono Nerd Font Mono"
    style: Regular

  bold:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold

  italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Italic

  # Point size of the font
  size: 15.0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

# github Alacritty Colors
colors:
    # Default colors
    primary:
        background: "#303446" # base
        foreground: "#C6D0F5" # text
        # Bright and dim foreground colors
        dim_foreground: "#C6D0F5" # text
        bright_foreground: "#C6D0F5" # text

    # Cursor colors
    cursor:
        text: "#303446" # base
        cursor: "#F2D5CF" # rosewater
    vi_mode_cursor:
        text: "#303446" # base
        cursor: "#BABBF1" # lavender

    # Search colors
    search:
        matches:
            foreground: "#303446" # base
            background: "#A5ADCE" # subtext0
        focused_match:
            foreground: "#303446" # base
            background: "#A6D189" # green
        footer_bar:
            foreground: "#303446" # base
            background: "#A5ADCE" # subtext0

    # Keyboard regex hints
    hints:
        start:
            foreground: "#303446" # base
            background: "#E5C890" # yellow
        end:
            foreground: "#303446" # base
            background: "#A5ADCE" # subtext0

    # Selection colors
    selection:
        text: "#303446" # base
        background: "#F2D5CF" # rosewater

    # Normal colors
    normal:
        black: "#51576D" # surface1
        red: "#E78284" # red
        green: "#A6D189" # green
        yellow: "#E5C890" # yellow
        blue: "#8CAAEE" # blue
        magenta: "#F4B8E4" # pink
        cyan: "#81C8BE" # teal
        white: "#B5BFE2" # subtext1

    # Bright colors
    bright:
        black: "#626880" # surface2
        red: "#E78284" # red
        green: "#A6D189" # green
        yellow: "#E5C890" # yellow
        blue: "#8CAAEE" # blue
        magenta: "#F4B8E4" # pink
        cyan: "#81C8BE" # teal
        white: "#A5ADCE" # subtext0

    # Dim colors
    dim:
        black: "#51576D" # surface1
        red: "#E78284" # red
        green: "#A6D189" # green
        yellow: "#E5C890" # yellow
        blue: "#8CAAEE" # blue
        magenta: "#F4B8E4" # pink
        cyan: "#81C8BE" # teal
        white: "#B5BFE2" # subtext1

    indexed_colors:
        - { index: 16, color: "#EF9F76" }
        - { index: 17, color: "#F2D5CF" }