tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: ↑·
    behind: ↓·
    staged: "+"
    modified: "~"
    untracked: "?"
  styles:
    state: ""
    branch: "#[fg=white]"
    staged: "#[fg=lightgreen]"
    modified: "#[fg=yellow]"
    untracked: "#[fg=red]"
    conflict: ""
    stashed: ""
    clean: ""
    divergence: ""
  layout: [branch, ' ', flags]
  options:
    branch_max_len: 0
    hide_clean: true
