[package]
disabled=true

[docker_context]
disabled=true

[git_branch]
disabled=true

[git_status]
disabled=true

[directory]
fish_style_pwd_dir_length=1
style = "blue bold dimmed"

[jobs]
disabled = true

[character] # The name of the module we are configuring is 'character'
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold green)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[❮](bold green)"
vimcmd_replace_symbol = "[❮](bold green)"
vimcmd_replace_one_symbol = "[❮](bold green)"

[aws]
symbol = "aws "

[golang]
symbol = "go "
version_format='v${major}'

[java]
symbol = "java "
version_format='v${major}'

[nodejs]
symbol = "node "
version_format='v${major}'

[python]
symbol = "py "
version_format='v${major}'

[rust]
symbol = "rs "
version_format='v${major}'